version: '3.3'

volumes:
  pg_data:
  static:
  media:
  
services:
  db:
    image: postgres:13.10
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: vitrazliv/foodgram_backend:latest
    env_file: ./.env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    restart: always
  
  frontend:
    image: vitrazliv/foodgram_frontend:latest
    env_file: ./.env
    command: cp -r /app/result_build/. /frontend_static/
    volumes:
      - ./frontend/:/app/result_build/
      
  nginx:
    image: vitrazliv/foodgram_gateway:latest
    env_file: ./.env
    ports:
      - "8000:80"
    volumes:
    #  - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
    restart: always